export const SERVICES = [
  {
    id: 'ac-service',
    name: 'AC Service',
    description: 'Cleaning, gas refill & repair',
    icon: 'Wind',
    basePrice: 499,
    category: 'appliance',
    color: 'from-blue-500/20 to-blue-600/10',
    iconColor: 'text-blue-400',
    features: ['Deep Cleaning', 'Gas Refill', 'Filter Wash', 'Cooling Check'],
    duration: '2-3 hrs',
    popular: true,
  },
  {
    id: 'cctv-installation',
    name: 'CCTV Installation',
    description: 'Camera setup & configuration',
    icon: 'Camera',
    basePrice: 1499,
    category: 'security',
    color: 'from-green-500/20 to-green-600/10',
    iconColor: 'text-green-400',
    features: ['HD Cameras', 'DVR Setup', 'Night Vision', 'Mobile Access'],
    duration: '3-4 hrs',
    popular: false,
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Pipe repair & installations',
    icon: 'Droplets',
    basePrice: 399,
    category: 'home',
    color: 'from-cyan-500/20 to-cyan-600/10',
    iconColor: 'text-cyan-400',
    features: ['Leak Fix', 'Pipe Repair', 'Tap Install', 'Drain Clear'],
    duration: '1-2 hrs',
    popular: false,
  },
  {
    id: 'electrician',
    name: 'Electrician',
    description: 'Wiring & electrical repairs',
    icon: 'Zap',
    basePrice: 349,
    category: 'home',
    color: 'from-yellow-500/20 to-yellow-600/10',
    iconColor: 'text-yellow-400',
    features: ['Wiring', 'Switchboard', 'Fan Install', 'MCB Repair'],
    duration: '1-2 hrs',
    popular: true,
  },
  {
    id: 'refrigerator-repair',
    name: 'Refrigerator Repair',
    description: 'Cooling & compressor service',
    icon: 'Thermometer',
    basePrice: 599,
    category: 'appliance',
    color: 'from-teal-500/20 to-teal-600/10',
    iconColor: 'text-teal-400',
    features: ['Cooling Fix', 'Compressor', 'Door Seal', 'Gas Charge'],
    duration: '2-3 hrs',
    popular: false,
  },
  {
    id: 'washing-machine',
    name: 'Washing Machine',
    description: 'Drum & motor servicing',
    icon: 'RefreshCw',
    basePrice: 449,
    category: 'appliance',
    color: 'from-orange-500/20 to-orange-600/10',
    iconColor: 'text-orange-400',
    features: ['Drum Clean', 'Motor Check', 'Inlet Fix', 'Error Codes'],
    duration: '2-3 hrs',
    popular: false,
  },
];

export const TIME_SLOTS = [
  '08:00 AM', '09:00 AM', '10:00 AM', '11:00 AM',
  '12:00 PM', '02:00 PM', '03:00 PM', '04:00 PM',
  '05:00 PM', '06:00 PM',
];

export const STATUS_CONFIG = {
  pending: { label: 'Pending', color: 'text-yellow-400', bg: 'bg-yellow-400/10', border: 'border-yellow-400/30' },
  confirmed: { label: 'Confirmed', color: 'text-blue-400', bg: 'bg-blue-400/10', border: 'border-blue-400/30' },
  in_progress: { label: 'In Progress', color: 'text-orange-400', bg: 'bg-orange-400/10', border: 'border-orange-400/30' },
  completed: { label: 'Completed', color: 'text-green-400', bg: 'bg-green-400/10', border: 'border-green-400/30' },
  cancelled: { label: 'Cancelled', color: 'text-red-400', bg: 'bg-red-400/10', border: 'border-red-400/30' },
};
